/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResidencyRouteImport } from './routes/residency'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiLegalAskRouteImport } from './routes/api/legal-ask'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiResidencyAskRouteImport } from './routes/api/residency-ask'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronCrawlRouteImport } from './routes/api/cron/crawl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencyRoute = ResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLegalAskRoute = ApiLegalAskRouteImport.update({
  id: '/api/legal-ask',
  path: '/api/legal-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResidencyAskRoute = ApiResidencyAskRouteImport.update({
  id: '/api/residency-ask',
  path: '/api/residency-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCrawlRoute = ApiCronCrawlRouteImport.update({
  id: '/api/cron/crawl',
  path: '/api/cron/crawl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/sources': typeof SourcesRoute
  '/api/ask': typeof ApiAskRoute
  '/api/legal-ask': typeof ApiLegalAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/sources': typeof SourcesRoute
  '/api/ask': typeof ApiAskRoute
  '/api/legal-ask': typeof ApiLegalAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/sources': typeof SourcesRoute
  '/api/ask': typeof ApiAskRoute
  '/api/legal-ask': typeof ApiLegalAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/sources'
    | '/api/ask'
    | '/api/legal-ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/cron/crawl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/sources'
    | '/api/ask'
    | '/api/legal-ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/cron/crawl'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/sources'
    | '/api/ask'
    | '/api/legal-ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/cron/crawl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  ContactRoute: typeof ContactRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResidencyRoute: typeof ResidencyRoute
  SourcesRoute: typeof SourcesRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiLegalAskRoute: typeof ApiLegalAskRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiResidencyAskRoute: typeof ApiResidencyAskRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronCrawlRoute: typeof ApiCronCrawlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residency': {
      id: '/residency'
      path: '/residency'
      fullPath: '/residency'
      preLoaderRoute: typeof ResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/legal-ask': {
      id: '/api/legal-ask'
      path: '/api/legal-ask'
      fullPath: '/api/legal-ask'
      preLoaderRoute: typeof ApiLegalAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/residency-ask': {
      id: '/api/residency-ask'
      path: '/api/residency-ask'
      fullPath: '/api/residency-ask'
      preLoaderRoute: typeof ApiResidencyAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/crawl': {
      id: '/api/cron/crawl'
      path: '/api/cron/crawl'
      fullPath: '/api/cron/crawl'
      preLoaderRoute: typeof ApiCronCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  ContactRoute: ContactRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResidencyRoute: ResidencyRoute,
  SourcesRoute: SourcesRoute,
  ApiAskRoute: ApiAskRoute,
  ApiLegalAskRoute: ApiLegalAskRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiResidencyAskRoute: ApiResidencyAskRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronCrawlRoute: ApiCronCrawlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
