/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResidencyRouteImport } from './routes/residency'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiResidencyAskRouteImport } from './routes/api/residency-ask'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencyRoute = ResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResidencyAskRoute = ApiResidencyAskRouteImport.update({
  id: '/api/residency-ask',
  path: '/api/residency-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/residency': typeof ResidencyRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/residency-ask': typeof ApiResidencyAskRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/api/ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/api/ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/forms'
    | '/login'
    | '/profile'
    | '/residency'
    | '/api/ask'
    | '/api/draft'
    | '/api/residency-ask'
    | '/api/stats'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResidencyRoute: typeof ResidencyRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiResidencyAskRoute: typeof ApiResidencyAskRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residency': {
      id: '/residency'
      path: '/residency'
      fullPath: '/residency'
      preLoaderRoute: typeof ResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/residency-ask': {
      id: '/api/residency-ask'
      path: '/api/residency-ask'
      fullPath: '/api/residency-ask'
      preLoaderRoute: typeof ApiResidencyAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResidencyRoute: ResidencyRoute,
  ApiAskRoute: ApiAskRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiResidencyAskRoute: ApiResidencyAskRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
