/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiStatsRouteImport } from './routes/api/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/stats': typeof ApiStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/stats': typeof ApiStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/stats': typeof ApiStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forms' | '/api/ask' | '/api/draft' | '/api/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forms' | '/api/ask' | '/api/draft' | '/api/stats'
  id: '__root__' | '/' | '/forms' | '/api/ask' | '/api/draft' | '/api/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormsRoute: typeof FormsRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiStatsRoute: typeof ApiStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormsRoute: FormsRoute,
  ApiAskRoute: ApiAskRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiStatsRoute: ApiStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
